spring:
  datasource:
    url: jdbc:mysql://localhost:3306/AB?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true

server:
  port: 8084


application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
